#!/bin/bash
# Check event_location in the most recent Auto Sync

echo "=========================================="
echo "Checking event_location in Auto Sync"
echo "=========================================="
echo ""

echo "Most recent Auto Syncs from 'auto sync check':"
echo "- Team Meeting (Running)"
echo "- Team Meeting (Paused)"
echo "- Second Test (Running)"
echo ""
echo "To verify event_location column exists and check values:"
echo ""
echo "Option 1: Check via Supabase Dashboard"
echo "  - Go to Table Editor > auto_syncs"
echo "  - Look for 'event_location' column"
echo "  - Check the most recent record"
echo ""
echo "Option 2: Run SQL query in Supabase SQL Editor:"
echo "  SELECT id, event_name, event_location, status, created_at"
echo "  FROM auto_syncs"
echo "  ORDER BY created_at DESC"
echo "  LIMIT 5;"
echo ""
echo "Option 3: If migration not applied, run:"
echo "  supabase db push"
echo "  OR manually execute:"
echo "  supabase/migrations/20260106134436_add_event_location_to_auto_syncs.sql"
echo ""
echo "Expected result:"
echo "  - event_location column should exist"
echo "  - Value should be NULL for existing records (no location provided)"
echo "  - New records can have event_location when provided in extracted_data"
echo ""

