#!/bin/bash
# Step-by-step curl test for creating Auto Sync
# Run each command one at a time and respond manually

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

source test_config.sh

echo "=========================================="
echo "Auto Sync Creation - Step by Step Test"
echo "=========================================="
echo ""
echo "Phone Number: $TEST_PHONE_NUMBER"
echo "Function URL: $FUNCTION_URL"
echo ""
echo "=========================================="
echo ""

# Step 1: Exit any current auto sync
echo "STEP 1: Exit any current auto sync setup"
echo "----------------------------------------"
echo "Run this command:"
echo ""
echo "curl -s -X POST \"$FUNCTION_URL\" \\"
echo "  -H \"Authorization: Bearer $SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"message\": \"exit\","
echo "    \"phone_number\": \"$TEST_PHONE_NUMBER\","
echo "    \"is_host\": true,"
echo "    \"send_sms\": false"
echo "  }' | python3 -m json.tool"
echo ""
echo "Press Enter when ready for next step..."
read

# Step 2: Start auto sync with crew name
echo ""
echo "STEP 2: Start Auto Sync with crew name"
echo "----------------------------------------"
echo "Run this command (replace 'Friends' with your crew name):"
echo ""
echo "curl -s -X POST \"$FUNCTION_URL\" \\"
echo "  -H \"Authorization: Bearer $SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"message\": \"auto sync Friends\","
echo "    \"phone_number\": \"$TEST_PHONE_NUMBER\","
echo "    \"is_host\": true,"
echo "    \"send_sms\": false"
echo "  }' | python3 -m json.tool"
echo ""
echo "Press Enter when ready for next step..."
read

# Step 3: Provide event name
echo ""
echo "STEP 3: Provide event name"
echo "----------------------------------------"
echo "Run this command (replace 'Test Event' with your event name):"
echo ""
echo "curl -s -X POST \"$FUNCTION_URL\" \\"
echo "  -H \"Authorization: Bearer $SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"message\": \"Test Event\","
echo "    \"phone_number\": \"$TEST_PHONE_NUMBER\","
echo "    \"is_host\": true,"
echo "    \"send_sms\": false"
echo "  }' | python3 -m json.tool"
echo ""
echo "Press Enter when ready for next step..."
read

# Step 4: Provide time (no calendar mode)
echo ""
echo "STEP 4: Provide time (no calendar mode)"
echo "----------------------------------------"
echo "Run this command (replace with your time, e.g., '1/10 6pm'):"
echo ""
echo "curl -s -X POST \"$FUNCTION_URL\" \\"
echo "  -H \"Authorization: Bearer $SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"message\": \"1/10 6pm\","
echo "    \"phone_number\": \"$TEST_PHONE_NUMBER\","
echo "    \"is_host\": true,"
echo "    \"send_sms\": false"
echo "  }' | python3 -m json.tool"
echo ""
echo "Press Enter when ready for next step..."
read

# Step 5: Select goal (1 = Everyone, 2 = Critical mass)
echo ""
echo "STEP 5: Select goal"
echo "----------------------------------------"
echo "Run this command (1 for Everyone, 2 for Critical mass):"
echo ""
echo "curl -s -X POST \"$FUNCTION_URL\" \\"
echo "  -H \"Authorization: Bearer $SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"message\": \"1\","
echo "    \"phone_number\": \"$TEST_PHONE_NUMBER\","
echo "    \"is_host\": true,"
echo "    \"send_sms\": false"
echo "  }' | python3 -m json.tool"
echo ""
echo "Press Enter when ready for next step..."
read

# Step 6: Send confirmation
echo ""
echo "STEP 6: Send Auto Sync"
echo "----------------------------------------"
echo "Run this command to send the Auto Sync:"
echo ""
echo "curl -s -X POST \"$FUNCTION_URL\" \\"
echo "  -H \"Authorization: Bearer $SUPABASE_ANON_KEY\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"message\": \"send\","
echo "    \"phone_number\": \"$TEST_PHONE_NUMBER\","
echo "    \"is_host\": true,"
echo "    \"send_sms\": false"
echo "  }' | python3 -m json.tool"
echo ""
echo "=========================================="
echo "Test complete!"
echo "=========================================="

